# todo: add config file and assigne based on it and label
name: AutoAssigner

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.DPRO_TOKEN }}
          debug: true
          script: |
            const labels = []
            const assignees = [context.actor]
            const developers = [
              'dmitry-prohorov', 
              'alex-pokolenko', 
              'alexey-filippov', 
              'alekseykosov93', 
              'sergeydzibuk', 
              'valentine-timohin', 
              'anasavitskaya', 
              'antonlashkov',
              'justmaaax',
              'kirillvasilovich',
              'pavel151194',
              'ryakovets',
              'makyform']
            const qa = ['vlasovakate', 'sfilipovi4', 'vimleshgupta1995', 'shekherdahiya', 'dberesnev']
            const management = [
              'brandon-marshall', 
              'chantellarmstrong', 
              'janetjonessumoscheduler', 
              'jasonnorth', 
              'kayla-howard',
              'paigebaileysumoscheduler',
              'angelamcknightsumoscheduler',
              'sergey-lepeshinkiy',
              'nick-zenko']
            if (developers.includes(context.actor.toLowerCase())) {
              labels.push('development')
            }
            if (qa.includes(context.actor.toLowerCase())) {
              assignees.push('dmitry-prohorov')
            }
            if (management.includes(context.actor.toLowerCase())) {
              assignees.push(...['sergey-lepeshinkiy', 'nick-zenko'])
            }
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: assignees.concat(context.payload.issue.assignees.map(assignee => assignee.login)).filter((e,i,a) => e && a.indexOf(e) === i),
              labels: labels.concat(context.payload.issue.labels.map(label => label.name)).filter((e,i,a) => e && a.indexOf(e) === i)
            })
